######################################################################
#
# Mark Higginbottom
#
# 05/12/2016
#
# Playbook to configure a centos7 gui vm with the Robot 
# Framework WebDemo
#
# NOTE: This is not the way to write an Ansible Playbook.
# It is just a quick and dirty script to get up and running quickly.
#
######################################################################
- name: Robot Framework Web Demo install 
  hosts: "{{ servers }}"
  become: Yes
  become_user: root
  tasks:
    - debug: "{{ servers }}"  
    - name: install the latest version of Python
      yum:
        name: python
        state: latest    

    - name: check python version
      shell: python --version
      register: shell_output
    - debug: var=shell_output.stderr
    - name: Check for pip install file
      stat: path=/home/vagrant/get-pip.py
      register: pip
    - block:
      - name: Fetch pip install file
        get_url:
          url: https://bootstrap.pypa.io/get-pip.py
          dest: /home/vagrant
      - name: Install pip
        command: python get-pip.py 
      - name: Install Robot Framework
        command: pip install robotframework       
      - name: Install selenium2 library
        command: pip install robotframework-selenium2library
      when: pip.stat.exists == False
      rescue:
      - debug: msg="ERROR - pip Robot Framework install failed"
      - name: remove web dir contents
        file: path=/home/vagrant/get-pip.py state=absent
    - name: install the latest version of Git
      yum:
        name: git
        state: latest
#
    - name: Check for Geckodriver
      stat: path=/usr/bin/geckodriver
      register: gecko
    - block:
      - name: Fetch Geckodriver install file and untar
        unarchive:
          src: https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
          dest: /usr/lib64
          remote_src: Yes
      - name: Link up Geckodriver
        file: 
          src: /usr/lib64/geckodriver 
          dest: /usr/bin/geckodriver
          state: link
      when: gecko.stat.exists == False
      rescue:
      - debug: msg="ERROR - unable to set up Geckodriver"
#
    - name: Check for Firefox
      stat: path=/usr/bin/firefox
      register: ff
    - fail: msg="ERROR - firefox not installed"
      when: ff.stat.exists == False
    - block:
      - name: check firefox version
        shell: firefox -v
        register: shell_output
      - debug: var=shell_output.stderr
      - name: install the latest version of firefox
        yum:
          name: firefox
          state: latest
      when: ff.stat.exists == True
      rescue:
      - debug: msg="ERROR - problem checking for firefox"
#
    - block: 
      - name: Clone Robot Framework webdemo
        git: 
          repo: https://bitbucket.org/robotframework/webdemo.git
          dest: /home/vagrant/webdemo
          clone: yes
      - name: Set permissions on webdemo to vagrant
        file: 
          dest: /home/vagrant/webdemo 
          owner: vagrant
          group: vagrant
          recurse: yes
